.\" Sample man page for CSCI 241
.\" Benjamin Kuperman - Fall 2011

.TH format 1 "October 31 2011" "CSCI 241" "Oberlin College"

.SH NAME
.B format - simple text formatter
\- an example of a sample man page

.SH SYNOPSIS
.B format
[ -FLAG ][OPTION]...
< filename

.SH DESCRIPTION
Does everything a sample man page should do.

.SH OPTIONS
.IP "-w <width>"
Specify the output width.
.IP"-r"
Output the text aligned on the right.
.IP"-j"
Output the text with justified alignment.
.IP"-h or -?"
Prints usage message.

.SH AUTHORS
Zack Sheldon and Sam Meizlish (Fall 2015)

.SH BUGS
MANY!
