.\" Man page for format
.\" Zachary Sheldon and Sam Meizlish

.TH format 1 "October 31 2011" "CSCI 241" "Oberlin College"

.SH NAME
.B format
\- - simple text formatter

.SH SYNOPSIS
.B format
[ -FLAG ][OPTION]...

.SH DESCRIPTION
Formats the output of text into neat paragraphs.

.SH OPTIONS
.IP "-w <width>"
Specify the output width.
.IP "-r"
Output the text aligned on the right.
.IP "-j"
Output the text with justified alignment.
.IP "-s"
Compresses multiple newlines into a single newline.
.IP "-h or -?"
Prints usage message.

.SH AUTHORS
Zack Sheldon and Sam Meizlish (Fall 2015)

.SH BUGS
MANY!
